name: Publish
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.14.0]
        steps:
            - run: echo published
