name: Tag
on:
    pull_request:
        types: [ closed ]
        branches:
            - main
            - development

permissions:
    contents: write

jobs:
    tag:
        if: ${{ github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'bump') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/tag
              with:
                  headref: ${{ github.head_ref }}
                  refname: ${{ github.ref_name }}
                  sha: ${{ github.sha }}
