name: Tag
on:
    pull_request:
        types: [closed]
        branches:
            - main

permissions:
    contents: write

#if: ${{ github.event.pull_request.merged && github.event.label.name == 'bump' }}

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - run: echo pull request was closed
            - run: echo ${{ toJson((contains(github.event.pull_request.labels.*.name, 'bump'))) }}
            - run: echo ${{ toJson(github.event.pull_request.merged) }}
