name: Tag
on:
    pull_request:
        branches:
            - main
        types: [closed]

permissions:
    contents: write

jobs:
    tag:
        if: ${{ github.event.pull_request.merged && github.event.label.name == 'bump' }}
        runs-on: ubuntu-latest
        steps:
            - run: echo a bump PR was merged to main. tagging
