name: Tag
on:
    push:
        branches:
            - main

permissions:
    contents: write

#if: ${{ github.event.pull_request.merged && github.event.label.name == 'bump' }}

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - run: echo a bump PR was merged to main
            - run: echo merged = ${{ github.event.pull_request.merged }}
            - run: echo label = ${{ github.event.label.name }}
