name: Tag
on:
    pull_request:
        types:
            - closed

permissions:
    contents: write

#if: ${{ github.event.pull_request.merged && github.event.label.name == 'bump' }}

jobs:
    tag:
        runs-on: ubuntu-latest
        steps:
            - run: echo pull request was closed
            - run: echo ${{ toJson(github.event.pull_request) }}
            - run: echo ${{ toJson(github.event.label) }}
